version: "3.9"
services:
  wiremock:
    image: wiremock/wiremock:3.5.3
    container_name: wiremock
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./wiremock:/home/wiremock
    command: --verbose