@tsid = 0{{$random.hexadecimal(12)}}

### GET /users - get all users
GET http://localhost:8080/users
Authorization: Bearer {{$auth.token("auth-id")}}

### POST /users - create user
POST http://localhost:8080/users
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{
  "username": "username",
  "email": "foobar@test.com"
}

### GET /users/{tsid} - get a user by id
GET http://localhost:8080/users/{{tsid}}
Authorization: Bearer {{$auth.token("auth-id")}}

### DELETE /users/{tsid} - delete a user by id
DELETE http://localhost:8080/users/{{tsid}}
Authorization: Bearer {{$auth.token("auth-id")}}