# This workflow will build and attach binaries to a new GitHub release when a release is created
name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Set OS/ARCH environment
        run: |
          echo "GOOS=${{ matrix.os }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build versioned binary
        run: |
          mkdir -p release
          BINARY_NAME="jetter-${VERSION}-${GOOS}"
          if [ "$GOOS" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          go build -o release/$BINARY_NAME main.go
          echo "Built $BINARY_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jetter-${{ matrix.os }}
          path: release/*

  attach-to-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Attach binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}