# This workflow will build and attach binaries to a new GitHub release when a release is created
name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get version from tag
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          mkdir -p build
          GOOS=linux   GOARCH=amd64 go build -o build/jetter-$VERSION-linux
          GOOS=linux   GOARCH=arm64 go build -o build/jetter-$VERSION-linux-arm64
          GOOS=darwin  GOARCH=amd64 go build -o build/jetter-$VERSION-darwin
          GOOS=darwin  GOARCH=arm64 go build -o build/jetter-$VERSION-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o build/jetter-$VERSION-windows.exe

      - name: Generate checksums
        run: |
          cd build
          sha256sum * > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: bin/*