name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get version from tag
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          
          if [ -z "$VERSION" ]; then
            echo "ERROR: VERSION could not be determined from $GITHUB_REF"
            exit 1
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          if [[ "$VERSION" == *alpha* ]] || [[ "$VERSION" == *beta* ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Build binaries
        run: |
          mkdir -p build
          GOOS=linux   GOARCH=amd64 go build -o build/jetter-$VERSION-linux
          GOOS=linux   GOARCH=arm64 go build -o build/jetter-$VERSION-linux-arm64
          GOOS=darwin  GOARCH=amd64 go build -o build/jetter-$VERSION-darwin
          GOOS=darwin  GOARCH=arm64 go build -o build/jetter-$VERSION-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o build/jetter-$VERSION-windows.exe

      - name: Generate checksums
        run: |
          cd build
          sha256sum * > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.VERSION }}
          prerelease: ${{ env.PRERELEASE }}
          files: build/*